# Generated by Django 5.2.2 on 2025-06-24 09:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_user_role"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="cover_picture",
            new_name="cover_photo",
        ),
    ]
